cp ../../../../gitsExternos/three_dev/build/three.js .
cp ../../../../gitsExternos/three_dev/examples/js/controls/OrbitControls.js ./controls/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/AMFLoader.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/ColladaLoader.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/MTLLoader.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/OBJLoader.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/OBJLoader2.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/STLLoader.js ./loaders/
cp ../../../../gitsExternos/three_dev/examples/js/loaders/LoaderSupport.js ./loaders/
